# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a10e964a00e5626e6469f0e6662714dfde3e5f5cb2db6499dc9f658881509f78dea7eb8d2c405ec9d5131097e19287a3277ee908d3d8ab42f4a6bc16caa37b

test:
  secret_key_base: 772b1eba7c6cd800ac59a99abb2ee69c2250db2ce8e6551ee42c859cf804b85fc48ec9f203f9031449a4aadd7047e0452d4e5ca63d869887cc51c5e6382737a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
