# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 116fee6fb72af9cc149c1d25f768845f3c59b810727aa3597a36469b2833659c161a61674488ff9f32909777355e8ffddd8e56990abe8fa36697f2d9e0ab7048

test:
  secret_key_base: ed97102208a69f24412833d9f33a5872ff32e609d9a40897a591fb36512c4c01037eeb5744591248406f12f15b7ba2a4a56dfd1028499b1a0d4004474b7a37ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
